algoritmo "Operadora"

var
   minutos:inteiro
   valor : real
   
inicio
       escreval("Digite a quantidade de minutos : ")
       leia(minutos)
       
       valor <- 50
       se minutos > 100 entao
          valor <- valor + 2 * (minutos - 100)
          
          fimse
          
          escreval("O valor a pagar é : ",valor)
      

      
      


      

      

fimalgoritmo

