algoritmo "pares_consecutivos"

var

   x , soma , contador : inteiro
   
inicio
      escreval("Digite um numero : ")
      leia(x)
      
      enquanto x <> 0 faca
      
      se x mod 2 <> 0 entao
         x <- x + 1
      fimse
      
      soma <- 5 * x + 20
      escreval("Soma = " ,soma)
      
      escreval("Digite um numero : ")
      leia(x)
      

      
      fimenquanto


      

fimalgoritmo
